version: "3.9"

services:
  #Backend
  backend:
    ports:
      - "9090:8080"
    image: backend
    build:
      context: .
      dockerfile: ./secure-cloud-backend/secure-cloud-api/Dockerfile
    env_file:
      - secure-cloud-backend/.env
    networks:
      - local_network
    depends_on:
      secureclouddb:
        condition: service_started

  #Fronted
  frontend:
    ports:
      - "8083:5173"
    build:
      context: .
      dockerfile: ./secure-cloud-frontend/Dockerfile
    volumes:
      - ./secure-cloud-frontend/src:/app/src:delegated
    networks:
      - local_network
    env_file:
      - secure-cloud-frontend/.env

  #Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    ports:
      - "8080:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    command: start-dev
    
  # Database  
  secureclouddb:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=SecureCloudDB
    ports:
      - '5432:5432'
    volumes:
      - secureclouddb_data:/data
    networks:
      - local_network

networks:
  local_network:
    driver: bridge

volumes:
  secureclouddb_data: